image: registry.git.cccv.de/uffd/docker-images/bookworm

variables:
  DEBIAN_FRONTEND: noninteractive 
  GIT_SUBMODULE_STRATEGY: normal
  APT_API_URL: https://packages.cccv.de
  APT_REPO: uffd
  PYLINT_PIN: pylint~=2.16.2

before_script:
  - python3 -V
  - lsb_release -a
  - uname -a
  - python3 -m pylint --version
  - python3 -m coverage --version
  - export PACKAGE_VERSION="$(git describe | sed -E -n -e 's/^v([0-9.]*)$/\1/p' -e 's/^v([0-9.]*)-([0-9]*)-g([0-9a-z]*)$/\1.dev+git.\3/p' | grep .)"

.build:
  stage: build

tests:buster:sqlite:
  image: registry.git.cccv.de/uffd/docker-images/buster
  stage: test
  needs: []
  script:
  - python3 -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

tests:bullseye:sqlite:
  image: registry.git.cccv.de/uffd/docker-images/bullseye
  stage: test
  needs: []
  script:
  - python3 -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

tests:bookworm:sqlite:
  image: registry.git.cccv.de/uffd/docker-images/bookworm
  stage: test
  needs: []
  script:
  - rm -rf pages
  - mkdir -p pages
  - cp -r uffd/static pages/static
  - DUMP_PAGES=pages python3-coverage run --include 'uffd/*.py' -m pytest --junitxml=report.xml || touch failed
  - sed -i -e 's/href="\/static\//href=".\/static\//g' -e 's/src="\/static\//src=".\/static\//g' pages/*.html || true
  - python3-coverage report -m
  - python3-coverage html
  - python3-coverage xml
  - test ! -e failed
  artifacts:
    when: always
    paths:
    - htmlcov/index.html
    - htmlcov
    - pages
    expose_as: 'Coverage Report'
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
